/*
-- Query: SELECT * FROM movies2017.movies
LIMIT 0, 1000

-- Date: 2018-03-31 00:22
*/
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (1,'It','9/8/2017',135,7.5,'69','In the summer of 1989, a group of bullied kids band together to destroy a shapeshifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.',327481748);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (2,'Get Out','2/24/2017',104,7.7,'84','A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',176040665);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (3,'Wonder Woman','6/2/2017',141,7.5,'76','When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.\n',412563408);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (4,'Lady Bird','12/1/2017',94,7.6,'94','In 2002, an artistically inclined seventeen-year-old girl comes of age in Sacramento, California.\n',48930150);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (5,'Dunkirk','7/21/2017',106,8,'94','Allied soldiers from Belgium, the British Empire and France are surrounded by the German Army, and evacuated during a fierce battle in World War II.',188045546);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (6,'Call Me by Your Name','1/19/2018',132,8,'93','In 1980s Italy, a romance blossoms between a seventeen year-old student and the older man hired as his father\'s research assistant.',17928521);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (7,'The Shape of Water','12/22/2017',123,7.5,'87','At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.\n',63403905);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (8,'Star Wars: The Last Jedi','12/15/17',152,7.4,'85','Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order.',620030903);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (9,'Phantom Thread','1/19/2018',130,7.8,'90','Set in 1950\'s London, Reynolds Woodcock is a renowned dressmaker whose fastidious life is disrupted by a young, strong-willed woman, Alma, who becomes his muse and lover.\n',20956300);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (10,'The Florida Project','11/10/17',111,7.7,'92','Set over one summer, the film follows precocious six-year-old Moonee as she courts mischief and adventure with her ragtag playmates and bonds with her rebellious but caring mother, all while living in the shadows of Walt Disney World.',5904366);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (11,'The Big Sick','7/14/2017',120,7.6,'86','Pakistan-born comedian Kumail Nanjiani and grad student Emily Gardner fall in love but struggle as their cultures clash. When Emily contracts a mysterious illness, Kumail finds himself forced to face her feisty parents, his family\'s expectations, and his true feelings.',42873127);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (12,'Thor: Ragnarok','11/3/2017',130,7.9,'74','Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök, the destruction of his world, which is at the hands of the powerful and ruthless villain Hela.',315058289);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (13,'Baby Driver','6/28/2017',112,7.7,'86','After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.',107825862);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (14,'The Post','1/12/2018',116,7.3,'83','A cover-up that spanned four U.S. Presidents pushed the country\'s first female newspaper publisher and a hard-driving editor to join an unprecedented battle between the press and the government.',81639452);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (15,'Blade Runner 2049','10/6/2017',164,8.1,'81','A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who\'s been missing for thirty years.',92054159);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (16,'Three Billboards Outside Ebbing, Missouri','12/1/17',115,8.2,'88','A mother personally challenges the local authorities to solve her daughter\'s murder when they fail to catch the culprit.\n',54185158);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (17,'A Ghost Story','7/27/17',92,6.9,'84','In this singular exploration of legacy, love, loss, and the enormity of existence, a recently deceased, white-sheeted ghost returns to his suburban home to try to reconnect with his bereft wife.',1596371);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (18,'The Disaster Artist','12/8/17',104,7.6,'76','When Greg Sestero, an aspiring film actor, meets the weird and mysterious Tommy Wiseau in an acting class, they form a unique friendship and travel to Hollywood to make their dreams come true.',21120616);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (19,'Logan','3/3/2017',137,8.1,'77','In the near future, a weary Logan cares for an ailing Professor X, somewhere on the Mexican border. However, Logan\'s attempts to hide from the world, and his legacy, are upended when a young mutant arrives, pursued by dark forces.',226277068);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (20,'War for the Planet of the Apes','7/14/17',140,7.5,'82','After the apes suffer unimaginable losses, Caesar wrestles with his darker instincts and begins his own mythic quest to avenge his kind.',146880162);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (21,'Justice League','11/17/17',120,6.7,'45','Fueled by his restored faith in humanity and inspired by Superman\'s selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince, to face an even greater enemy.',229024295);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (22,'Coco','11/21/17',105,8.5,'81','Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',209425871);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (23,'Spider-Man: Homecoming','7/7/2017',133,7.5,'73','Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.',334201140);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (24,'Guardians of the Galaxy Vol. 2','5/5/2017',136,7.7,'67','The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill\'s true parentage.',389813101);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (25,'John Wick: Chapter 2','2/10/2017',122,7.5,'75','After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life.\n',92029184);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (26,'Baywatch','5/25/2017',116,5.6,'37','Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit, as they uncover a criminal plot that threatens the future of the bay.',58060186);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (27,'Beauty and the Beast','3/17/2017',129,7.3,'65','An adaptation of the fairy tale about a monstrous-looking prince and a young woman who fall in love.\n',504014165);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (28,'Alien: Covenant','5/19/2017',122,6.5,'65','The crew of a colony ship, bound for a remote planet, discover an uncharted paradise with a threat beyond their imagination, and must attempt a harrowing escape.\n',74262031);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (29,'The LEGO Batman Movie','2/10/2017',104,7.3,'75','A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.\n',175750384);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (30,'Brawl in Cell Block 99','10/6/2017',132,7.2,'79','A former boxer-turned-drug runner lands in a prison battleground after a deal gets deadly.\n',NULL);
INSERT INTO `movies` (`idMovies`,`title`,`year`,`runtime`,`imdb-rating`,`metascore`,`description`,`gross`) VALUES (31,'Mudbound','11/17/2017',134,7.5,'85','Two men return home from World War II to work on a farm in rural Mississippi, where they struggle to deal with racism and adjusting to life after war.\n',NULL);
