/*
-- Query: SELECT * FROM movies2017.directors
LIMIT 0, 1000

-- Date: 2018-03-31 00:21
*/
INSERT INTO `directors` (`idDirectors`,`name`,`about`) VALUES (1,'Andy Muschietti','Andy Muschietti is a director and writer, known for Mama (2013), It (2017) and Mamá (2008)');
INSERT INTO `directors` (`idDirectors`,`name`,`about`) VALUES (2,'Jordan Peele','Jordan Peele attended the Computer School in I.S. 44 for Junior High School and went on to attend The Calhoun School for high school, graduating in 1997. He then went on to attend Sarah Lawrence College as a member of the class of 2001. His mother is white and his father is black. Jordan is married to comedian Chelsea Peretti, with whom he has a daughter.');
INSERT INTO `directors` (`idDirectors`,`name`,`about`) VALUES (3,'Patty Jenkins','Patty Jenkins is a writer/director best known for directing Wonder Woman, the Warner Bros./DC Comics blockbuster of 2017, and her debut feature Monster. Patty also works in television where she is best known for the pilot and finale episode of AMC\'s hit show The Killing.\nPatty began her career as a painter at The Cooper Union in New York City. Upon transitioning to filmmaking, she spent eight years as an Assistant Camera Person/Focus Puller on commercials and music videos. After attending the AFI in Los Angeles, she wrote and directed Monster.\n\nRoger Ebert named Monster as The #1 Best Film of 2004 and #3 Best Film of the decade. AFI named it on the Ten Best Films of the Year. Patty also garnered a number of awards and nominations, including winning Best First Feature at the 2004 Independent Spirit Awards. Charlize Theron went on to sweep the awards circuit winning the Oscar, Golden Globe, SAG Award, and numerous critics\' awards in the Best Actress category.\n\nJenkins went on to direct many commercials and TV programs including Fox\'s Arrested Development and HBO\'s Entourage and the pilot episodes for ABC\'s Betrayal and Exposed. She won the DGA award for best directing for The Killing pilot, as well as being nominated for an Emmy. She also received an Emmy nomination for her work on the final segment of FIVE - a series of short films about breast cancer.\nIn 2017, Jenkins broke the record for Biggest Grossing Live-Action Film Directed by a Woman, Domestic and Worldwide, with Wonder Woman. The film also received critical acclaim, broke several records and went on to become highest grossing film of the summer of 2017.');
INSERT INTO `movies2017`.`directors` (`idDirectors`, `name`, `about`) VALUES ('4', 'Greta Gerwig', 'Greta Gerwig is an American actress, playwright, screenwriter, and director. She has collaborated with Noah Baumbach on several films, including Greenberg (2010), Frances Ha (2012), for which she earned a Golden Globe nomination, and Mistress America (2015). Gerwig made her solo directorial debut with the critically acclaimed comedy-drama film Lady Bird (2017), which she also wrote, and has also had starring roles in the films Damsels in Distress (2011), Jackie (2016), and 20th Century Women (2016).');
INSERT INTO `movies2017`.`directors` (`idDirectors`, `name`, `about`) VALUES ('5', 'Christopher Nolan', 'Best known for his cerebral, often nonlinear storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970 in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made.');
INSERT INTO `movies2017`.`directors` (`idDirectors`, `name`, `about`) VALUES ('6', 'Luca Guadagnino', 'Luca Guadagnino was born in 1971 in Palermo, Sicily, Italy. He is a director and producer, known for Call Me by Your Name (2017), I Am Love (2009) and A Bigger Splash (2015).');
