/*
-- Query: SELECT * FROM movies2017.company
LIMIT 0, 1000

-- Date: 2018-03-31 00:21
*/
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (100,'New Line Cinema','New Line Cinema is an American film production label of Warner Bros. Entertainment that was founded in 1967 by Robert Shaye as a film distribution company, later becoming an independent film studio. It became a subsidiary of the Turner Broadcasting System in 1994 before Turner merged with Time Warner in 1996, and was later merged with its larger sister studio Warner Bros. Entertainment in 2008.[1] Currently, its films are distributed by Warner Bros.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (101,' RatPac-Dune Entertainment','RatPac Entertainment is an American motion picture production and financing company owned by producer-director Brett Ratner and Access Entertainment. RatPac was founded by Ratner and billionaire James Packer. RatPac is a partner in RatPac-Dune Entertainment with Dune Entertainment.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (102,' Vertigo Entertainment','Vertigo Entertainment is an American film and television production company based in Los Angeles, founded in 2001 by Roy Lee and Doug Davison.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (103,' Universal Pictures','Universal Pictures (also referred to as Universal Studios or simply Universal) is an American film studio owned by Comcast through the Universal Filmed Entertainment Group division of its wholly owned subsidiary NBCUniversal.[2] The company was founded in 1912 by Carl Laemmle, Mark Dintenfass, Charles O. Baumann, Adam Kessel, Pat Powers, William Swanson, David Horsley, Robert H. Cochrane, and Jules Brulatour, and is the oldest surviving film studio in the United States, the world\'s fourth oldest after Gaumont, Pathé and Nordisk Film, and the oldest in terms of the overall film market[citation needed]. Its studios are located in Universal City, California, and its corporate offices are located in New York City.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (104,' Blumhouse Productions','Blumhouse Productions is an American film and television production company, founded in 2000 by Jason Blum.[1] Blumhouse produces low-budget horror films, such as Get Out, Insidious, The Purge, Split, Paranormal Activity, Unfriended, Sinister, Creep and The Gift.[2][3] In 2014, Blumhouse produced the Academy Award–winning film Whiplash, for which Blum was nominated for the Academy Award for Best Picture.[4] In 2014, the company had signed a 10-year first-look deal with Universal Pictures.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (105,'Warner Bros.','Warner Bros. Entertainment Inc. (formerly Warner Brothers Pictures, Inc.)[6] is an American entertainment company that is a division of Time Warner and is headquartered in Burbank, California. It is one of the \"Big Six\" major American film studios.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (106,'Atlas Entertainment ','Atlas Entertainment is an American film financing and production company, started by Charles Roven and Dawn Steel in 1995.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (107,'Cruel and Unusual Films','Cruel and Unusual Films, Inc. is an American film production company that was established in 2004 by filmmaker Zack Snyder, his wife Deborah Snyder, and their producing partner Wesley Coller');
