/*
-- Query: SELECT * FROM movies2017.company
LIMIT 0, 1000

-- Date: 2018-03-31 00:21
*/
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (100,'New Line Cinema','New Line Cinema is an American film production label of Warner Bros. Entertainment that was founded in 1967 by Robert Shaye as a film distribution company, later becoming an independent film studio. It became a subsidiary of the Turner Broadcasting System in 1994 before Turner merged with Time Warner in 1996, and was later merged with its larger sister studio Warner Bros. Entertainment in 2008.[1] Currently, its films are distributed by Warner Bros.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (101,' RatPac-Dune Entertainment','RatPac Entertainment is an American motion picture production and financing company owned by producer-director Brett Ratner and Access Entertainment. RatPac was founded by Ratner and billionaire James Packer. RatPac is a partner in RatPac-Dune Entertainment with Dune Entertainment.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (102,' Vertigo Entertainment','Vertigo Entertainment is an American film and television production company based in Los Angeles, founded in 2001 by Roy Lee and Doug Davison.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (103,' Universal Pictures','Universal Pictures (also referred to as Universal Studios or simply Universal) is an American film studio owned by Comcast through the Universal Filmed Entertainment Group division of its wholly owned subsidiary NBCUniversal.[2] The company was founded in 1912 by Carl Laemmle, Mark Dintenfass, Charles O. Baumann, Adam Kessel, Pat Powers, William Swanson, David Horsley, Robert H. Cochrane, and Jules Brulatour, and is the oldest surviving film studio in the United States, the world\'s fourth oldest after Gaumont, Pathé and Nordisk Film, and the oldest in terms of the overall film market[citation needed]. Its studios are located in Universal City, California, and its corporate offices are located in New York City.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (104,' Blumhouse Productions','Blumhouse Productions is an American film and television production company, founded in 2000 by Jason Blum.[1] Blumhouse produces low-budget horror films, such as Get Out, Insidious, The Purge, Split, Paranormal Activity, Unfriended, Sinister, Creep and The Gift.[2][3] In 2014, Blumhouse produced the Academy Award–winning film Whiplash, for which Blum was nominated for the Academy Award for Best Picture.[4] In 2014, the company had signed a 10-year first-look deal with Universal Pictures.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (105,'Warner Bros.','Warner Bros. Entertainment Inc. (formerly Warner Brothers Pictures, Inc.)[6] is an American entertainment company that is a division of Time Warner and is headquartered in Burbank, California. It is one of the \"Big Six\" major American film studios.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (106,'Atlas Entertainment ','Atlas Entertainment is an American film financing and production company, started by Charles Roven and Dawn Steel in 1995.');
INSERT INTO `company` (`idCompany`,`name`,`about`) VALUES (107,'Cruel and Unusual Films','Cruel and Unusual Films, Inc. is an American film production company that was established in 2004 by filmmaker Zack Snyder, his wife Deborah Snyder, and their producing partner Wesley Coller');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`, `about`) VALUES ('108', 'Scott Rudin Productions', 'Scott Rudin (born July 14, 1958)[1] is an American film and theatre producer. In the 1980s, he formed his own production company called Scott Rudin Productions, and his first film was Gillian Armstrong’s Mrs. Soffel. Soon after, he joined 20th Century-Fox as an executive producer, and eventually became president of production, a post he held for almost 15 years. He has since made films under the Touchstone Pictures, Walt Disney Pictures, and Miramax labels, among others. In 2012, Rudin became one of the few people who have won an Emmy, Grammy, Oscar, and Tony Award, and the first producer to do so.');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`) VALUES ('109', 'Entertainment 360');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`, `about`) VALUES ('110', 'IAC Films', 'IAC (InterActiveCorp) is an American holding company, that owns over 150 brands across 100 countries, mostly in media and Internet[3] headquartered in New York City.[4] Joey Levin, who previously led the company\'s Search & Applications segment,[5] has been the company\'s Chief Executive Officer since June 2015');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`, `about`) VALUES ('111', 'Syncopy', 'Syncopy Films Inc. is a British film production company based in London, England. The company was founded by film director, screenwriter and producer Christopher Nolan and his wife Emma Thomas. The name Syncopy Films derives from \"syncope\", the medical term for fainting or loss of consciousness');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`) VALUES ('112', 'Dombey Street Productions');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`) VALUES ('113', 'Frenesy Film Company');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`) VALUES ('114', 'La Cinéfacture');
INSERT INTO `movies2017`.`company` (`idCompany`, `name`) VALUES ('115', 'RT Features');
